version: "3.9"
services:
  multiprocess-demo:
    build:
      context: ../
      dockerfile: code_process/Dockerfile
    container_name: multiprocess-demo
    command: ["python", "multiprcs.py"]
  multithread-demo:
    build:
      context: ../
      dockerfile: code_process/Dockerfile
    container_name: multithread-demo
    command: ["python", "multithreads.py"]
  ice-server:
    build:
      context: ../
      dockerfile: code_process/Dockerfile
    container_name: ice-server
    command: ["python", "ice_server.py"]
    ports:
      - "11000:11000"
  ice-client:
    build:
      context: ../
      dockerfile: code_process/Dockerfile
    container_name: ice-client
    depends_on:
      - ice-server
    command: ["sh", "-c", "sleep 2 && python ice_client.py"]