version: "3.9"
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    restart: unless-stopped
  mqtt-pub:
    build:
      context: ../
      dockerfile: MQTT/Dockerfile
    container_name: mqtt-publisher
    depends_on:
      - mqtt-broker
    environment:
      - BROKER=mqtt-broker
    entrypoint: ["sh", "-c", "sleep 3 && python pub.py"]
  mqtt-sub:
    build:
      context: ../
      dockerfile: MQTT/Dockerfile
    container_name: mqtt-subscriber
    depends_on:
      - mqtt-broker
    environment:
      - BROKER=mqtt-broker
    command: ["python", "sub.py"]